### ISSUE TITLE
README TODO

### ISSUE THREAD

**Issue by whitead** [Future-House/aviary#85]
- [x] Messages - rewrite this section to be about env/agent
- [x] Move API keys to developer section (since they're discussed in the context of unit tests)
- [x] Check async vs sync. Things like reset are async now, I think
- [x] `export_frame` - let's not make this abstract; no one uses it
- [x] Move README for individual environments to their subdirectories; in the main README, just provide a one-sentence overview, install command, and link to the README
- [x] [?] Can we hide type hinting from the examples? It would reduce clutter and information density. We can just mention in a section that the library is fully typed
- [x] Add Jupyter Notebook/Colab notebook section - include Python 3.11 install and note that async can be used in notebooks
